#!/usr/bin/env ruby

require File.expand_path('../manager', __FILE__)

class Php < Manager
  include Plugin::List
  # Needs to be included last of the main_case plugins
  include Plugin::Set

  include Plugin::Use
  include Plugin::Reset
end

_php = Php.new("php")
_php.build
