#!/usr/bin/env ruby

require File.expand_path('../lib/manager', __FILE__)
require File.expand_path('../contrib/zsh', __FILE__)

class Python < Manager
  include PosixProxy
  if ENV['_VM_USE_ZSH']
    include Contrib::ZSH
  end

  name "python"

  create_fragment("PYTHONPATH")
  include Plugin::List
  # Needs to be included last of the main_case plugins
  include Plugin::Set

  include Plugin::Python::Reset
  include Plugin::Python::Use
end

_python = Python.new
_python.build
