#!/usr/bin/env ruby

require File.expand_path('../lib/manager', __FILE__)
require File.expand_path('../contrib/installer', __FILE__)
require File.expand_path('../contrib/zsh', __FILE__)

class Ruby < Manager
  include PosixProxy
  if ENV['_VM_USE_ZSH']
    include Contrib::ZSH
  end

  name "ruby"

  include Plugin::List
  include Contrib::Installer("ruby-build")
  # Needs to be included last of the main_case plugins
  include Plugin::Set

  include Plugin::Ruby::Use
  include Plugin::Ruby::Reset
end

_ruby = Ruby.new
_ruby.build
